Cf 878 automatic bagging
usdot-fhwa-stol/cda1tenth-bringup pull request #14
Opened 2024-06-18 18:41 UTC by john-chrosniak

# PR Details
## Description

This PR adds logic to optionally record a ROS2 bag on the C1T trucks during system bringup. The parameters used for each bag are also copied to the bag directory.

## Related Jira Key

TODO

## Motivation and Context

In order to track how parameter changes impact system performance, we need to record data from the vehicle for future analysis and ensure that the parameters used for each run are tracked as well.

## How Has This Been Tested?

TODO

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-06-18 21:06 UTC, willjohnsonk requested changes

2024-06-18 21:06 UTC, willjohnsonk commented on launch/ros2_rosbag.launch.py
> +    bag_dir = '/home/' + getpass.getuser() + '/bags/rosbag2_' + str(datetime.now().strftime('%Y-%m-%d_%H%M%S'))
getpass seems to work but I would leverage os since you're already using it with something `os. path. expanduser()` or one of the other ways os can do that instead

2024-06-18 21:06 UTC, willjohnsonk commented on launch/ros2_rosbag.launch.py
> +    bag_dir = '/home/' + getpass.getuser() + '/bags/rosbag2_' + str(datetime.now().strftime('%Y-%m-%d_%H%M%S'))
I'd also suggest using a different directory than just "bags" in case that is already in use. Maybe something like "c1t_bags"

2024-06-18 21:06 UTC, willjohnsonk commented on launch/ros2_rosbag.launch.py
> +        shell='true'
shell=true is generally a bad practice, would try to work around this if possible.

2024-06-18 21:06 UTC, willjohnsonk commented on launch/ros2_rosbag.launch.py
> +def on_shutdown(event, context):
is this just copying the params file to the bag directory? is there a reason for this?

2024-06-18 21:06 UTC, willjohnsonk commented on launch/ros2_rosbag.launch.py
> +def on_shutdown(event, context):
I see the reasoning to have an associated params file from the run but it looks like this will just constantly overwrite that file so no history will be preserved

2024-06-18 21:20 UTC, john-chrosniak commented on launch/ros2_rosbag.launch.py
> +    bag_dir = '/home/' + getpass.getuser() + '/bags/rosbag2_' + str(datetime.now().strftime('%Y-%m-%d_%H%M%S'))
Switched to `os.getlogin()`

2024-06-18 21:20 UTC, john-chrosniak commented on launch/ros2_rosbag.launch.py
> +    bag_dir = '/home/' + getpass.getuser() + '/bags/rosbag2_' + str(datetime.now().strftime('%Y-%m-%d_%H%M%S'))
Switched to `c1t_bags`

2024-06-18 21:21 UTC, john-chrosniak commented on launch/ros2_rosbag.launch.py
> +        shell='true'
Good point, just removed this and confirmed it wasn't required for bag recording

2024-06-18 21:23 UTC, john-chrosniak commented on launch/ros2_rosbag.launch.py
> +def on_shutdown(event, context):
This writes it to the directory for each bag (i.e. `~/c1t_bags/rosbag2_2024-06-18_171743/params.yaml`)

2024-06-19 16:10 UTC, willjohnsonk approved these changes

2024-06-19 16:16 UTC, merged